name: Build GZDoom for ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build GZDoom
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            libgtk-3-dev \
            libsdl2-dev \
            libfreetype6-dev \
            zlib1g-dev \
            libjpeg-dev \
            libbz2-dev \
            libfluidsynth-dev \
            libopenal-dev \
            libgme-dev \
            libmpg123-dev \
            libsndfile1-dev \
            libwildmidi-dev \
            libsqlite3-dev \
            timidity \
            nasm \
            python3 \
            python3-pip \
            ninja-build \
            clang \
            libvulkan-dev \
            libgl1-mesa-dev

      - name: Set Up CMake Toolchain for ARM64
        run: |
          echo "set(CMAKE_SYSTEM_NAME Linux)" > arm64-toolchain.cmake
          echo "set(CMAKE_SYSTEM_PROCESSOR aarch64)" >> arm64-toolchain.cmake
          echo "set(CMAKE_C_COMPILER clang)" >> arm64-toolchain.cmake
          echo "set(CMAKE_CXX_COMPILER clang++)" >> arm64-toolchain.cmake

      - name: Configure Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../arm64-toolchain.cmake -G Ninja

      - name: Build GZDoom
        run: |
          cd build
          ninja

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gzdoom-arm64
          path: build/
